#Datosestaticos
def listarProductos():
    print("Marcas del vehiculo")
    print("--------------------")
    print("1.BMW Group")
    print("2. General Motors")
    print("3. Honda")
    print("4. Hyundai Motor Company")
    print("5. Mazda")
    print("6. Nissan")
    print("7. Pagani")
    print("8. Ferrari")
    print("9. Lamborgini")
    print("10. Audi")
    print("11. Infiniti")
    print("12. Renault")
    print("13. Alfa Romeo")
    print("14. Acura")
    print("15. Aston Martin")
    print("16. Bentley")
    print("17. Cadillac")
    print("18. Lamborgini")
    print("19. Lamborgini")
    print("20. Lamborgini")
 

